### ISSUE TITLE
Feature request: add other rough.js fillStyles 😁

### ISSUE THREAD

**Issue by batpigandme** [xvrdm/ggrough#1]
Having so much fun with this (it's Mara/[at]dataandme, btw) – was just looking at the rough.js API, and noticed they've added new [fill styles](https://github.com/pshihn/rough#filling): hatched, zigzag, and dots. Personally, I dig the dots, but (having not made any htmlwidgets 😱) I don't know how hard it is to add new styles! So, consider this an optimistic, but totally non-urgent feature request!

Keep on rocking it!
Mara

**Comment by xvrdm** [comment]
Wow I cannot keep up with them: I missed that! It should be easy enough (much easier than supporting SVG and more geoms 😅 ), since the lib is already setup for two (hachure and solid). Will add soon.

**Comment by xvrdm** [comment]
Just merged #2 . The new styles all work in GeomCol (as long as you keep the roughness for dots at 1). Dots give me troubles for GeomArea but the other ones (zigzag and cross-hatch) seem ok. I will try to do more testing and create a better gallery (if you want to contribute examples, feel free 😄 ).

**Comment by batpigandme** [comment]
Woooo! Awesome. I'm crunching on a talk for Tuesday, but I'm planning a blog post sometime next week, so I'll be sure to make 'em self-contained examples!
